export const BUILT_IN_MOB_STAT_KEYS = [
  "armor",
  "shields",
  "energy",
  "power",
  "evasion",
  "energy_regen_rate",
  "shield_regen",
  "armor_regen",
  "targeting",
  "threat_generation",
  "hacking",
  "damage_reflect",
  "damage_reduction",
  "stealth",
  "sensors",
  "salvage_bonus",
  "heat_resistance",
  "speed",
  "overclock",
  "lootbox_count",
] as const;

export const MOB_NUMERIC_FIELDS = [
  "level",
  "item_drop_chance",
  "mod_drop_chance",
  "min_mod_rarity",
  "max_mod_rarity",
  "repair_cost",
  "mob_end",
] as const;

export const MOB_BOOLEAN_FIELDS = [
  "can_attack",
  "hail_can_hail_target",
  "is_vendor",
  "item_no_duplicates",
  "mod_no_duplicates",
  "poi_require_discovery",
  "poi_show",
] as const;

export const MOB_KNOWN_TOP_LEVEL_FIELDS = [
  "id",
  "display_name",
  "scene",
  "sprite",
  "faction",
  "level",
  "abilities",
  "ai_type",
  "can_attack",
  "comms_directory",
  "hail_can_hail_target",
  "hail_greeting",
  "hail_image",
  "hail_name",
  "hail_portrait",
  "is_vendor",
  "item_drop_chance",
  "item_loot_table",
  "item_no_duplicates",
  "max_mod_rarity",
  "merchant_profile",
  "min_mod_rarity",
  "mob_end",
  "mob_tag",
  "mod_drop_chance",
  "mod_loot_table",
  "mod_no_duplicates",
  "poi_require_discovery",
  "poi_show",
  "repair_cost",
  "scan",
  "scene",
  "services",
  "sprite",
  "stats",
] as const;

export const MOB_SORT_OPTIONS = [
  { value: "display_name", label: "Display Name" },
  { value: "id", label: "ID" },
  { value: "level", label: "Level" },
  { value: "faction", label: "Faction" },
  { value: "ai_type", label: "AI Type" },
] as const;
